language: java
sudo: required
services:
- docker
jdk:
- openjdk8
branches:
  only:
  - master
  - develop
os:
- linux
install: true
script: mvn -q clean install

before_deploy:
- bash ./ci/before_deploy.sh

deploy:
  provider: script
  script: bash ./ci/deploy.sh
  on:
    branch: master
    tags: true
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email: dev-notify@lockss.org
  
before_install:
- openssl aes-256-cbc -K $encrypted_6155405dce59_key -iv $encrypted_6155405dce59_iv
  -in ci/codesigning.asc.enc -out ci/codesigning.asc -d
env:
  global:
  - secure: WmmP7/ATo6aGCIwCwDW6h4l0ACzzuDMI0/blaPTvmVLd4ZhE1gpV+JVOQn3cC/zlt3ZfyXfNUUjkt2Wy7y9KCkOFYX8/MP28RsJ2Xxnyro8sqgngcT22e6OnPV5pLzpaXtNKnUvdvda6Dt8wuLc987iunbfcy3h2wTZ15NgoIeV/5kr27JKCku+z0s9+pplx4pX87Qrd6U9z7b6nEtOBSPxnCTCi2oWfUpNbBXPtRzExgVuVI6yMv9d7LBgPLtdhAfjs201yd3gYVcRQshUadrwAn9OkdZ1reLrNC4GMPrfZcWK1tDwEVPmaaxmHcYiSlBkZlRlz2s84y+ETM/HQ1xQXvRm/TufkIT5owt0Y+AnJVR3Q6wo+3Y8WLTJDSBB5VP60kt/nbIgcTgJCeMOXbZQFUphaCuwv/Lv7ABUF1qZT13Ak0tjRt88MyNZyLp9HicP/CAjru61ANGzRY4qQjfvZ1pbj9hb0wsf6bAJnQprfYdKbr1eh8o+raPBuk7gjXt6JVOeVZ+frK4bBitmR0ru4PMs5Ytwq55S0WIi5j3gyJHXlFxEYKYuWGSsarxkL4PMMmaliNJNSgcur8BF84F3PToFPvOImYBOX2/06bWnSC45+aK226tcpzNXEYcR9JV+o/Y1A+VMz9bA9S/wrQjnsFS2vNRBgBP8FzX+hr+g=
  - secure: c5Nun1VAr2ddr+zkHb/hfOhHsFnaeS/gY895oylBFdI1R2mTIn1XmDfCNqjy+W7XwLjnYcGCJ0D0tc49HW4rKWWRIRv9FmcBSJnRo6dwVv54fCQrC1ezV7qt1vM+8+nWgUAEoCEJflSrdYQPfbPs9XWmjWnAfTxvUxK907UYfkfM0ZoCJBhs7oNLKFE/cMJysJr6COOHXSI0NR4LjJBiEalfYVMedR8ZiaxRydBzRHk85UGvKQyvNRnA3dBvz0Br+yqrqo0FKOqt81kJK9xD/+GljB+52b8T7fQDKrcYmWpxqQFPhuQTg57TcA3VXqwu3boh7CqsborS46HeVsvfompmzAjeN9uesNCl1ArMTag0um6osXCy3V2A2mtp0aaat5FSaEgpyCZm/TDsjYTtjkaKRKOH6/7bxfFPRbZNhIXT111MPYrWjrtzB35omUYhwJU0qYIAcnd0umZRvZ5qoqxd6Kc3/L3Cz1UYsMxv1vUAYpjtr4tB5cOGQDrEqGxzkCmOAi8JCObnROaNaIS6Z1ESsu6A6/tJxTRPd62Xn2u999zlPfaYpB9fMOt4UVn0sxOrh+37KVk4LQoO2o3vWPdr3TkRIT4XcKtbYY2gh3aaXPjeLAtgrGzdXtvBlqUMG2E07+NxMwDLqPYmIE6Kcs3EOqIzVTUsVaF2FFRCSQs=
  - secure: Lrgwdg8gKCwF+Jleo70WWX7qX9lmwMpS1dntaQOO3ADyk565QscmIM5U7kEnG9XLtDXLYz9TLdoB8GznqzvQ6afpOxAg9tM/zanv7W8h6o6gy9yR0/4Vtl18sE09q4tdhTMtGtk0pDXG+U4LXQHoxvgToWXTNgo3IvSzOqWfR2JQ5GkDpZRLqT+qluPjdD3CGMP7ilZm1Dmjf5tKw+J6xxE8Et2bicJ3LaGFTK00CxAB8YzPysFTbnV/FdJfCpr16dzSdWYnPhKjiCVGUFjk3HI0jLiUgbrft3wwElKc5YlwVt5Ax8fhExotgaafM9pebGSSey4hNFEUo0+eNiaW4y3bPzXuXNjwYqVA7oi6R6sOzyT2CAPnRXggFHANSRx2lDRJOlvG0nBiloReQE/Ca6tq0gh6HDysFhHZK1BxEouKhbfuOaQmJp/NPDe31Q1BTZBtuYHM40+V4TpzbVsr0tR8om48JtLGkstISvlJOMqB9HYgsDRTw0pQ/FMjCU6lcfQcYY8PAQ7k8eg5coFMtTuqOWJ67PrjCA1nLPslPAIBrC6es1uGScadEWYcstFitrpzEopTBqtEfUVLz/ekJv4fFSUcJd4M7V+EUQCKTRWqhi3ozakJpmp2Vb5yrk4ruYDjXStTxM8CPiRTpQqtPpROgiBXgvb6x5ic7DaDQfA=
  - secure: nt7TmU4uU0cf76xPsr3tpXhPfCe34UDgPITQogBP8LR+LU7JzpWEgekfVgJ6S5VAg80m2IdcEDTF4fra0f/w/iBJiHU+TV5CU23+tM5vTXdmbkXAScev+yMHAYqcAU6WULbhjb9OVUB6unYwBNmppJ0JuLjeA5Hst47mIbQGUO8r6abG+TpEZwx2YDGSAiiqq00UBz3Tuoptns4NTVseP3/TxOi3prYlwb62hndXQ9EJ860AyjWFtXvcTctr+EKCt7jSWfN3U6XjDs886s2OFMLTuGNOYMV0Y5iNBsS9FxYW8AwS/PLvVDXGPeWLWAtDAfTi7Lp0iZzvJGe6SxsEu9w36NSbsDHSccLEC07GrJp4V5viCVxnO5SYn9nmxdn7a/rivhKf/MkdL9lds1XyNtIi+sQjQg+uAPwxbEasgsUkzxUYBNH3qhiuk410L5JY1iiwVcMkNeavLs5mPsuX5WBowrxESIW5axA2e/MzCzQzaMk52xCODppJBNr6kUQrar4h0qIYtjPjlfAAQoRKtszk71giQJ3rOPmPNOkY52HxUTIbf3xRPmIJm0cjrIlAxq+YN71klDF/JOzExukreVc3leNTawdskt7wIgqjBT3kDrqAwIoZj815xfYNuI+MZmWOB7WMEE0YNwGz+8jZPAHkxiSDsXKmlkH4F9YRIBk=
  - secure: biu33hmGP29KKHEePqlOTdH9LYkmJZG/ShsOHXSmPPKQ4kOTqsdWNfR/zgKtXlDxuEXC25/rq0T6wyDT6bTWBrw/IUWe3UBB8niXBe6dRCp3CECqDU7utrWD499O3X/mMy1P9zvnkK7F4pYt22QQ2FhM37n+7Azs+FSDwthBL9f0VEA9+7qOZEEhzIiaOHVOU5PITF61gxqLHMRMQ63D5oJt9+QcNZahMLFZO3L6rPy3/hmF5hjeY0F4mR3Vm4jttFImy+CCy6Rdape4qlk5JpOo8zM6o/rgBq9M7Dhux84zJ2qxS5eOv+6cHCFpLjECobywgYVDZXn3zPMHp82/u1yU9p2TUCx0v7+jRcypX7ZFAWKNaSRWLVW5JFh/JKkx8MpuPL+WduHzIzk9dRrk9qlBwejkBz7uZaDPTvQZr9BbrwJqck82Dvqdt71pmHwPGKN5M+kjiuvOFRJY5I7P38WfnmXbKa5Rkvv2WCvpFOmusrNBkQx1wsY3axUcsiQJRWoDlE4Idelshc6bukBKVrbyXuBqM1inWdcvdmOGo3VbHHoSZqJjM8PPsRXa8ijqH34kwkCXEeO4XCFV4y9McQGSRCFVM3sRi7mgN8od9qX6sJjZ5DuFQiaXwX+totaN3+XetX+06zHBXBYF9G7zs1GQyJho2tQCd6sHCUBQ+Rc=
  - secure: sXNLeLP3yY0SYgEgNjEJlxWt4G5+EdKP1/FoS/B7dMZ4Uf4jb6qkdMRHXqxReS9pD7PMI5RD72zWhmK/vTFTIcR3FxhvDOVGpR6RdxRDhxKv8Z4XWMlp+xM81eLCC8BB/j617bRQfcnH0M5f14kl0kSF1tMbiVkKxLzgT5ZKy/eBbp5okbLetQ0oqsn1TW6YezP4SZKS848Vyo3fCJ96DZl8m4/nTb14eevg8d8tBWnO+psGlqkooxy3cM75NI/ekFciQFQ55KLhydAjWMKro/9BO9doKoWkZw/Bs5Jf0AoAtysZz05ZgByntoBdubHY5OXPzpqNpUzjHqEkaSs20uL3CC+SPDFFymA+Lqkyy4ndFicy9rwbTp58RaPaKE61XSF5/OlzE34rbYPvBzLslHu2L7ARjElvbr8tclxbAUS3rqek0WHyCabWOBkbZ8v1ZeNebHw4VdYZCkhsDIoMXVMhtuXBVb2QUQOeEtJBkK0DwCTZ9+mTLDVTIXIqVzeUNOObLGkm3NR7mHxJSSqY5dPpsJ7xUZh30YcvyBfl5NWfPtCAIStFHHxDPMrGvGAECAQCA/MloG9xaoVRwwH71PqP0moxS8LrQZPnBwPfsAl7Az/98dKS7VAUeKmXAFQ6aJlDMrO9FkBlFt7EDGUwvJOZpkJCg5y2Nse3Nb2sEMo=
