#!/bin/bash
# Copyright (c) 2017 Board of Trustees of Leland Stanford Jr. University,
# all rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# STANFORD UNIVERSITY BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
# IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# Except as contained in this notice, the name of Stanford University shall not
# be used in advertising or otherwise to promote the sale, use or other dealings
# in this Software without prior written authorization from Stanford University.
#
# Make sure we have an updated laaws-daemon git branch
echo "Initializing laaws-daemon submodule...\n"
git submodule init
git submodule update
cd laaws-daemon
git checkout snafl-changes
echo "Building LAAWS jars...\n"
#ant jar-lockss
#ant jar-plugins
ant tdb-pln -Dplnname=prod
cd ..
ln -s laaws-daemon/test/frameworks/tdbxml
# make sure we install the missing mvn jars
# the LAAWS libs we use
echo "Installing LAAWS jars to maven repo...\n"
mvn install:install-file -Dfile=laaws-daemon/lib/lockss.jar -DpomFile=poms/lockss-2017.pom 
mvn install:install-file -Dfile=laaws-daemon/lib/lockss-plugins.jar -DpomFile=poms/lockss-plugins-2017.pom

# run maven build and test
echo "Running build and tests..."
mvn clean package
echo "Initialization is now complete!"
