#!/bin/bash

# Copyright (c) 2000-2025, Board of Trustees of Leland Stanford Jr. University
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Fixes the code generated by Swagger Codegen.

function fixImport() {
JAVA_SRC=$1
sed -i.backup "s/import $2/import $3/" $JAVA_SRC && rm $JAVA_SRC.backup
}

# Edit StatusApiDelegate.java.
STATUS_API_DELEGATE=src/generated/java/org/lockss/laaws/config/api/StatusApiDelegate.java
fixImport $STATUS_API_DELEGATE org.lockss.laaws.config.model.ApiStatus org.lockss.util.rest.status.ApiStatus

# Edit StatusApi.java.
STATUS_API=src/generated/java/org/lockss/laaws/config/api/StatusApi.java
fixImport $STATUS_API org.lockss.laaws.config.model.ApiStatus org.lockss.util.rest.status.ApiStatus

# Edit AusApiDelegate.java.
AUS_API_DELEGATE=src/generated/java/org/lockss/laaws/config/api/AusApiDelegate.java
fixImport $AUS_API_DELEGATE org.lockss.laaws.config.model.AuConfiguration org.lockss.config.AuConfiguration
fixImport $AUS_API_DELEGATE org.lockss.laaws.config.model.RequestAuControlResult org.lockss.ws.entities.RequestAuControlResult

# Edit AusApi.java.
AUS_API=src/generated/java/org/lockss/laaws/config/api/AusApi.java
fixImport $AUS_API org.lockss.laaws.config.model.AuConfiguration org.lockss.config.AuConfiguration
fixImport $AUS_API org.lockss.laaws.config.model.RequestAuControlResult org.lockss.ws.entities.RequestAuControlResult

# Edit ConfigApiDelegate.java.
CONFIG_API_DELEGATE=src/generated/java/org/lockss/laaws/config/api/ConfigApiDelegate.java
fixImport $CONFIG_API_DELEGATE org.lockss.laaws.config.model.PlatformConfigurationWsResult org.lockss.ws.entities.PlatformConfigurationWsResult

# Edit AusApi.java.
CONFIG_API=src/generated/java/org/lockss/laaws/config/api/ConfigApi.java
fixImport $CONFIG_API org.lockss.laaws.config.model.PlatformConfigurationWsResult org.lockss.ws.entities.PlatformConfigurationWsResult

# Edit AustatusesApiDelegate.java.
AUSTATUSES_API_DELEGATE=src/generated/java/org/lockss/laaws/config/api/AustatusesApiDelegate.java
fixImport $AUSTATUSES_API_DELEGATE org.lockss.laaws.config.model.AuStatus org.lockss.ws.entities.AuStatus

# Edit AustatusesApi.java.
AUSTATUSES_API=src/generated/java/org/lockss/laaws/config/api/AustatusesApi.java
fixImport $AUSTATUSES_API org.lockss.laaws.config.model.AuStatus org.lockss.ws.entities.AuStatus

# Edit AusubstancesApiDelegate.java.
AUSUBSTANCES_API_DELEGATE=src/generated/java/org/lockss/laaws/config/api/AusubstancesApiDelegate.java
fixImport $AUSUBSTANCES_API_DELEGATE org.lockss.laaws.config.model.CheckSubstanceResult org.lockss.ws.entities.CheckSubstanceResult

# Edit AusubstancesApi.java.
AUSUBSTANCES_API=src/generated/java/org/lockss/laaws/config/api/AusubstancesApi.java
fixImport $AUSUBSTANCES_API org.lockss.laaws.config.model.CheckSubstanceResult org.lockss.ws.entities.CheckSubstanceResult

# Edit WsApiDelegate.java.
WS_API_DELEGATE=src/generated/java/org/lockss/laaws/config/api/WsApiDelegate.java
fixImport $WS_API_DELEGATE org.lockss.laaws.config.model.AuWsResult org.lockss.ws.entities.AuWsResult
fixImport $WS_API_DELEGATE org.lockss.laaws.config.model.PluginWsResult org.lockss.ws.entities.PluginWsResult
fixImport $WS_API_DELEGATE org.lockss.laaws.config.model.TdbAuWsResult org.lockss.ws.entities.TdbAuWsResult
fixImport $WS_API_DELEGATE org.lockss.laaws.config.model.TdbPublisherWsResult org.lockss.ws.entities.TdbPublisherWsResult
fixImport $WS_API_DELEGATE org.lockss.laaws.config.model.TdbTitleWsResult org.lockss.ws.entities.TdbTitleWsResult
fixImport $WS_API_DELEGATE org.lockss.laaws.config.model.ContentConfigurationResult org.lockss.ws.entities.ContentConfigurationResult

# Edit WsApi.java.
WS_API=src/generated/java/org/lockss/laaws/config/api/WsApi.java
fixImport $WS_API org.lockss.laaws.config.model.AuWsResult org.lockss.ws.entities.AuWsResult
fixImport $WS_API org.lockss.laaws.config.model.PluginWsResult org.lockss.ws.entities.PluginWsResult
fixImport $WS_API org.lockss.laaws.config.model.TdbAuWsResult org.lockss.ws.entities.TdbAuWsResult
fixImport $WS_API org.lockss.laaws.config.model.TdbPublisherWsResult org.lockss.ws.entities.TdbPublisherWsResult
fixImport $WS_API org.lockss.laaws.config.model.TdbTitleWsResult org.lockss.ws.entities.TdbTitleWsResult
fixImport $WS_API org.lockss.laaws.config.model.ContentConfigurationResult org.lockss.ws.entities.ContentConfigurationResult
