#!/bin/bash
#
# Copyright (c) 2018-2020 Board of Trustees of Leland Stanford Jr. University,
# all rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# STANFORD UNIVERSITY BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
# IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# Except as contained in this notice, the name of Stanford University shall not
# be used in advertising or otherwise to promote the sale, use or other dealings
# in this Software without prior written authorization from Stanford University.
#

# Fixes the code generated by Swagger Codegen.

# Edit StatusApiDelegate.java.
STATUS_API_DELEGATE=src/generated/java/org/lockss/laaws/config/api/StatusApiDelegate.java
sed -i.backup "s/import org.lockss.laaws.config.model.ApiStatus/import org.lockss.util.rest.status.ApiStatus/" $STATUS_API_DELEGATE && rm $STATUS_API_DELEGATE.backup

# Edit StatusApi.java.
STATUS_API=src/generated/java/org/lockss/laaws/config/api/StatusApi.java
sed -i.backup "s/import org.lockss.laaws.config.model.ApiStatus/import org.lockss.util.rest.status.ApiStatus/" $STATUS_API && rm $STATUS_API.backup

# Edit AusApiDelegate.java.
AUS_API_DELEGATE=src/generated/java/org/lockss/laaws/config/api/AusApiDelegate.java
sed -i.backup "s/import org.lockss.laaws.config.model.AuConfiguration/import org.lockss.config.AuConfiguration/" $AUS_API_DELEGATE && rm $AUS_API_DELEGATE.backup
sed -i.backup "s/import org.lockss.laaws.config.model.ContentConfigurationResult/import org.lockss.ws.entities.ContentConfigurationResult/" $AUS_API_DELEGATE && rm $AUS_API_DELEGATE.backup
sed -i.backup "s/import org.lockss.laaws.config.model.RequestAuControlResult/import org.lockss.ws.entities.RequestAuControlResult/" $AUS_API_DELEGATE && rm $AUS_API_DELEGATE.backup

# Edit AusApi.java.
AUS_API=src/generated/java/org/lockss/laaws/config/api/AusApi.java
sed -i.backup "s/import org.lockss.laaws.config.model.AuConfiguration/import org.lockss.config.AuConfiguration/" $AUS_API && rm $AUS_API.backup
sed -i.backup "s/import org.lockss.laaws.config.model.ContentConfigurationResult/import org.lockss.ws.entities.ContentConfigurationResult/" $AUS_API && rm $AUS_API.backup
sed -i.backup "s/import org.lockss.laaws.config.model.RequestAuControlResult/import org.lockss.ws.entities.RequestAuControlResult/" $AUS_API && rm $AUS_API.backup

# Edit ConfigApiDelegate.java.
CONFIG_API_DELEGATE=src/generated/java/org/lockss/laaws/config/api/ConfigApiDelegate.java
sed -i.backup "s/import org.lockss.laaws.config.model.PlatformConfigurationWsResult/import org.lockss.ws.entities.PlatformConfigurationWsResult/" $CONFIG_API_DELEGATE && rm $CONFIG_API_DELEGATE.backup

# Edit AusApi.java.
CONFIG_API=src/generated/java/org/lockss/laaws/config/api/ConfigApi.java
sed -i.backup "s/import org.lockss.laaws.config.model.PlatformConfigurationWsResult/import org.lockss.ws.entities.PlatformConfigurationWsResult/" $CONFIG_API && rm $CONFIG_API.backup

# Edit TdbausApiDelegate.java.
TDBAUS_API_DELEGATE=src/generated/java/org/lockss/laaws/config/api/TdbausApiDelegate.java
sed -i.backup "s/import org.lockss.laaws.config.model.TdbAuWsResult/import org.lockss.ws.entities.TdbAuWsResult/" $TDBAUS_API_DELEGATE && rm $TDBAUS_API_DELEGATE.backup

# Edit TdbausApi.java.
TDBAUS_API=src/generated/java/org/lockss/laaws/config/api/TdbausApi.java
sed -i.backup "s/import org.lockss.laaws.config.model.TdbAuWsResult/import org.lockss.ws.entities.TdbAuWsResult/" $TDBAUS_API && rm $TDBAUS_API.backup

# Edit TdbtitlesApiDelegate.java.
TDBTITLES_API_DELEGATE=src/generated/java/org/lockss/laaws/config/api/TdbtitlesApiDelegate.java
sed -i.backup "s/import org.lockss.laaws.config.model.TdbTitleWsResult/import org.lockss.ws.entities.TdbTitleWsResult/" $TDBTITLES_API_DELEGATE && rm $TDBTITLES_API_DELEGATE.backup

# Edit TdbtitlesApi.java.
TDBTITLES_API=src/generated/java/org/lockss/laaws/config/api/TdbtitlesApi.java
sed -i.backup "s/import org.lockss.laaws.config.model.TdbTitleWsResult/import org.lockss.ws.entities.TdbTitleWsResult/" $TDBTITLES_API && rm $TDBTITLES_API.backup

# Edit TdbpublishersApiDelegate.java.
TDBPUBLISHERS_API_DELEGATE=src/generated/java/org/lockss/laaws/config/api/TdbpublishersApiDelegate.java
sed -i.backup "s/import org.lockss.laaws.config.model.TdbPublisherWsResult/import org.lockss.ws.entities.TdbPublisherWsResult/" $TDBPUBLISHERS_API_DELEGATE && rm $TDBPUBLISHERS_API_DELEGATE.backup

# Edit TdbpublishersApi.java.
TDBPUBLISHERS_API=src/generated/java/org/lockss/laaws/config/api/TdbpublishersApi.java
sed -i.backup "s/import org.lockss.laaws.config.model.TdbPublisherWsResult/import org.lockss.ws.entities.TdbPublisherWsResult/" $TDBPUBLISHERS_API && rm $TDBPUBLISHERS_API.backup

# Edit PluginsApiDelegate.java.
PLUGINS_API_DELEGATE=src/generated/java/org/lockss/laaws/config/api/PluginsApiDelegate.java
sed -i.backup "s/import org.lockss.laaws.config.model.PluginWsResult/import org.lockss.ws.entities.PluginWsResult/" $PLUGINS_API_DELEGATE && rm $PLUGINS_API_DELEGATE.backup

# Edit PluginsApi.java.
PLUGINS_API=src/generated/java/org/lockss/laaws/config/api/PluginsApi.java
sed -i.backup "s/import org.lockss.laaws.config.model.PluginWsResult/import org.lockss.ws.entities.PluginWsResult/" $PLUGINS_API && rm $PLUGINS_API.backup

# Edit AuqueriesApiDelegate.java.
AUQUERIES_API_DELEGATE=src/generated/java/org/lockss/laaws/config/api/AuqueriesApiDelegate.java
sed -i.backup "s/import org.lockss.laaws.config.model.AuWsResult/import org.lockss.ws.entities.AuWsResult/" $AUQUERIES_API_DELEGATE && rm $AUQUERIES_API_DELEGATE.backup

# Edit AuqueriesApi.java.
AUQUERIES_API=src/generated/java/org/lockss/laaws/config/api/AuqueriesApi.java
sed -i.backup "s/import org.lockss.laaws.config.model.AuWsResult/import org.lockss.ws.entities.AuWsResult/" $AUQUERIES_API && rm $AUQUERIES_API.backup

# Edit AustatusesApiDelegate.java.
AUSTATUSES_API_DELEGATE=src/generated/java/org/lockss/laaws/config/api/AustatusesApiDelegate.java
sed -i.backup "s/import org.lockss.laaws.config.model.AuStatus/import org.lockss.ws.entities.AuStatus/" $AUSTATUSES_API_DELEGATE && rm $AUSTATUSES_API_DELEGATE.backup

# Edit AustatusesApi.java.
AUSTATUSES_API=src/generated/java/org/lockss/laaws/config/api/AustatusesApi.java
sed -i.backup "s/import org.lockss.laaws.config.model.AuStatus/import org.lockss.ws.entities.AuStatus/" $AUSTATUSES_API && rm $AUSTATUSES_API.backup
