# Copyright (c) 2017 Board of Trustees of Leland Stanford Jr. University,
# all rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# STANFORD UNIVERSITY BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
# IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# Except as contained in this notice, the name of Stanford University shall not
# be used in advertising or otherwise to promote the sale, use or other dealings
# in this Software without prior written authorization from Stanford University.
#
swagger: '2.0'
info:
  description: API of Configuration Service for LAAWS
  version: 1.0.0
  title: LAAWS Configuration Service API
  termsOfService: http://www.lockss.org/terms/
  contact:
    name: 'LOCKSS Support'
    url: 'http://www.lockss.org/'
    email: 'support@lockss.org'
  license:
    name: 'Modified BSD License'
    url: 'http://www.lockss.org/support/open-source-license/'
host: 'laaws.lockss.org:443'
basePath: /
tags:
  - name: Default
    description: Default section
  - name: config
    description: Tasks on the configuration
  - name: aus
    description: Tasks on the configuration
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
security:
  - basicAuth: []
paths:
  '/config':
    put:
      tags:
        - config
      summary: Store configuration items
      description: Store the given key/value pairs
      operationId: putConfig
      consumes: []
      produces:
        - application/json
      parameters:
        - name: 'properties'
          in: body
          description: The configuration items to be stored
          required: true
          schema:
            $ref: '#/definitions/properties'
      responses:
        '200':
          description: The configuration items
          schema:
            $ref: '#/definitions/properties'
        '500':
          description: Internal server error
        '503':
          description: Some or all of the system is not available
    get:
      tags:
        - config
      summary: Get the configuration
      description: Get the full stored configuration
      operationId: getConfig
      consumes: []
      produces:
        - application/json
      responses:
        '200':
          description: The configuration items
          schema:
            $ref: '#/definitions/properties'
        '500':
          description: Internal server error
        '503':
          description: Some or all of the system is not available
  '/aus/{auid}':
    get:
      tags:
        - aus
      summary: Get the title database of an AU
      description: Get the title database of an AU given the AU identifier
      operationId: getTdbAu
      consumes: []
      produces:
        - application/json
      parameters:
        - name: 'auid'
          in: path
          description: The identifier of the AU for which the title database is requested
          required: true
          type: string
      responses:
        '200':
          description: The title database of the specified AU
          schema:
            $ref: '#/definitions/properties'
        '404':
          description: AU not found
        '500':
          description: Internal server error
        '503':
          description: Some or all of the system is not available
definitions:
  properties:
    type: object
    description: The map of items.
    additionalProperties:
      type: string
      description: The value of the configuration for the key.
